# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.7'

gem 'pry'
gem 'pry-byebug'
gem 'anima', '~> 0.3.2'
gem 'concord', '~> 0.1.6'
gem 'rspec', '~> 3.4'
gem 'snapshoot', path: '../'
